config/routes.rb
Rails.application.routes.draw do
  get 'entries/index'
  get 'entries/show'
  get 'entries/new'
  get 'entries/edit'
  resources :entries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def create
    entry = Entry.create(entry_params)

    redirect_to entries_path
  end
  
  def edit
    @entry = Entry.find(params[:id])
  end
  
  def update
    @entry = Entry.find(params[:id])
    @entry.update(entry_params)
    
    redirect_to entries_path(@entry)
  end

  private

  def entry_params
    params.require(:entry).permit(:name, :score, :date)
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/edit.html.erb
<h3>Update Entry Details</h3>
<%= form_with model: @entry do |form| %>
    <%= form.text_field :name, placeholder: "name" %>
    <%= form.text_field :score, placeholder: "score" %>
    <%= form.text_field :date, placeholder: "date" %>

  <%= form.submit %>
<% end %>

app/views/entries/index.html.erb
<table>
  <% @entries.each do |entry| %>
    <tr>
      <td><%= link_to entry.name, entry_path(entry) %></td>
      <td><%= button_to 'Edit', edit_entry_path(entry), method: 'get'%></td>
      <td><%= button_to 'Remove', entry_path(entry), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Entry", new_entry_path %>

app/views/entries/new.html.erb
<h3>Create an Entry</h3>
<%= form_with model: @entry do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :score, placeholder: "score" %>
  <%= form.text_field :date, placeholder: "date" %>

  <%= form.submit %>
<% end %>

<!-- <%= form_for @entry do |form| %>
  <%= form.text_field :name, placeholder: 'name' %>
  <%= form.text_field :score, placeholder: 'score' %>
  <%= form.text_field :date, placeholder: 'date' %>
  <%= form.submit %>
<% end %> -->

app/views/entries/show.html.erb
<h2><%= @entry.name %></h2>
<h1><%= @entry.score %></h1>
<h4><%= @entry.date %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyCrudApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>